development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: wttj_test_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: wttj_test_production
