development:
  adapter: redis
  url: redis://127.0.0.1:6379/1
  channel_prefix: wttj_test_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://127.0.0.1:6379/1
  channel_prefix: wttj_test_production
